config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :competitions, only: [:new, :create]
  resources :estates
  resources :wines do
    resources :tastings do
      resources :tasting_aromas
    end
  end
  get "wine_to_taste" => "wines#wine_to_taste"
  get "wine_tasted" => "wines#wine_tasted"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <% if current_user.facebook_picture_url? %>
          <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to estates_path do %>
                <i class="fa fa-user"></i> <%= t(".domaines", default: "Domaines") %>
              <% end %>
            </li>
            <li>
              <%= link_to wines_path do %>
                <i class="fa fa-home"></i>  <%= t(".vins", default: "Vins") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <li>
          <%= link_to new_competition_path do %>
            Competition new
          <% end %>
        </li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_radio_button_choice.html.erb
<div class="radio-button-choice">
  <div class="rg-btn rg-btn-choice active" id="short-tasting">
    Short tasting
  </div>
  <div class="rg-btn rg-btn-choice" id="long-tasting">
    Long tasting
  </div>
</div>

app/views/shared/_show_competition_card.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%= pluralize @competitions == nil ? 0 : @competitions.count, "concurrent" %></div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Concurrent</th>
        <th>Qté</th>
        <th>Prix Vin</th>
        <th>Prix Transport</th>
        <th>Prix Total</th>
      </tr>
    </thead>
    <tbody>
      <% @competitions.each do |compet| %>
        <% compet.competition_price_stages.each do |price| %>
        <tr>
          <td><%= compet.competitor if !compet.competitor.nil? %></td>
          <td><%= price.conditionning %></td>
          <td><%= price.wine_price %></td>
          <td><%= price.transport_price %></td>
          <% @price = price.wine_price + price.transport_price %>
          <td><%= @price %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_show_eye_tasting_comment.html.erb
<div class="show-tasting-comment-card text-center">
  <div>
    <div class="white-circle" id="oeil">
      <%= image_tag "oeil.svg" %>
    </div>
    <div class="tasting-description">
      <% unless tasting.eye_color == "" %>
        <div class="show-tasting-group">
          <div class="show-tasting-group-label">Couleur</div>
          <div class="show-tasting-group-value" id="show-tasting-group-color">
            <%= tasting.eye_color %>
          </div>
        </div>
      <% end %>
      <% unless tasting.eye_intensity.nil? %>
        <div class="show-tasting-group">
          <div class="show-tasting-group-label">Intensité</div>
          <div class="show-tasting-group-value">
            <div class="scale-background">
              <div id="sweetness-value" class="scale-value" style="width: <%= tasting.eye_intensity.to_f / 3 * 100 %>%"></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_show_general_tasting_comment.html.erb
<div class="show-tasting-comment-card text-center">
  <div>
    <div class="white-circle" id="sommelier">
      <%= image_tag "sommelier.svg" %>
    </div>
    <div class="tasting-description">
      <% unless tasting.general_mark.nil? %>
        <div class="show-tasting-group">
          <div class="show-tasting-group-label">Note Globale</div>
          <div class="show-tasting-group-value"  id="show-tasting-group-mark"><%= tasting.general_mark %></div>
        </div>
      <% end %>
      <div class="show-tasting-group">
        <div class="show-tasting-group-label">Dégusté le</div>
        <div class="show-tasting-group-value">
          <%= tasting.created_at.strftime("%d %B %Y") %>
        </div>
      </div>
      <% unless tasting.description == "" %>
        <div class="show-tasting-group">
          <div class="show-tasting-group-label">Général</div>
          <div class="show-tasting-group-value">
            <%= tasting.description %>
          </div>
        </div>
      <% end %>
      <% unless tasting.readiness.nil? %>
        <div class="show-tasting-group">
          <div class="show-tasting-group-label">Evolution</div>
          <div class="show-tasting-group-value">
            <%= tasting.readiness %>
          </div>
        </div>
      <% end %>
      <% unless tasting.stars_rating(tasting.balance).nil? %>
        <div class="show-tasting-group">
          <div class="show-tasting-group-label has-popover">
            <span>Equilibre</span>
          </div>
          <div class="star-center">
            <% tasting.stars_rating(tasting.balance)[0].times do %>
              <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
            <% tasting.stars_rating(tasting.balance)[1].times do %>
              <i class="fa fa-star-half-o" aria-hidden="true"></i>
            <% end %>
            <% tasting.stars_rating(tasting.balance)[2].times do %>
              <i class="fa fa-star-o" aria-hidden="true"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_show_nose_tasting_comment.html.erb
<div class="show-tasting-comment-card text-center">
  <div>
    <div class="white-circle" id="nez">
      <%= image_tag "nez.svg" %>
    </div>
    <div class="tasting-description">
      <% unless tasting.nose_quality.nil? %>
        <div class="show-tasting-group">
          <div class="star-center">
            <% tasting.stars_rating(tasting.nose_quality)[0].times do %>
              <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
            <% tasting.stars_rating(tasting.nose_quality)[1].times do %>
              <i class="fa fa-star-half-o" aria-hidden="true"></i>
            <% end %>
            <% tasting.stars_rating(tasting.nose_quality)[2].times do %>
              <i class="fa fa-star-o" aria-hidden="true"></i>
            <% end %>
          </div>
        </div>
      <% end %>
      <% unless tasting.nose_condition == "" %>
        <div class="show-tasting-group">
          <div class="show-tasting-group-label">Conditions</div>
          <div class="show-tasting-group-value" id="show-tasting-group-color">
            <span><%= tasting.nose_condition %></span>
          </div>
        </div>
      <% end %>
      <% unless tasting.nose_development == "" %>
        <div class="show-tasting-group">
          <div class="show-tasting-group-label">Développement</div>
          <div class="show-tasting-group-value" id="show-tasting-group-color">
            <span><%= tasting.nose_development %></span>
          </div>
        </div>
      <% end %>
      <% unless tasting.nose_intensity.nil? %>
        <div class="show-tasting-group">
          <div class="show-tasting-group-label">Intensité</div>
          <div class="show-tasting-group-value">
            <div class="scale-background">
              <div id="sweetness-value" class="scale-value" style="width: <%= tasting.nose_intensity.to_f / 5 * 100 %>%"></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_show_tasting_card.html.erb
<div class="show-tasting-card">
  <div class="show-tasting-characteristics">
    <div class="show-tasting-group">
      <div class="show-tasting-group-label">Couleur</div>
      <div class="show-tasting-group-value" id="show-tasting-group-color">
        <span><%= tasting.eye_color %></span>
      </div>
    </div>
    <div class="show-tasting-group">
      <div class="show-tasting-group-label has-popover">
        <span>Douceur<i class="fa fa-info-circle" aria-hidden="true"></i></span>
        <div class="rg-popo-bottom">
          <div class="rg-popo hidden">
            Plus le vin est doux, plus il est sucré.
          </div>
        </div>
      </div>
      <div class="show-tasting-group-value">
        <div class="scale-background">
          <div id="sweetness-value" class="scale-value" style="width: <%= tasting.palate_sweetness.to_f / 5 * 100 %>%"></div>
        </div>
      </div>
    </div>
    <div class="show-tasting-group">
      <div class="show-tasting-group-label has-popover">
        <span>Fraicheur<i class="fa fa-info-circle" aria-hidden="true"></i></span>
        <div class="rg-popo-bottom">
          <div class="rg-popo hidden">
            La fraicheur du vin, c'est son acidité. Et l'acidité, c'est ce qui fait saliver !
          </div>
        </div>
      </div>
      <div class="show-tasting-group-value">
        <div class="scale-background">
          <div id="acidity-value" class="scale-value" style="width: <%= tasting.palate_acidity.to_f / 5 * 100 %>%"></div>
        </div>
      </div>
    </div>
    <div class="show-tasting-group">
      <div class="show-tasting-group-label has-popover">
        <span>Tanins<i class="fa fa-info-circle" aria-hidden="true"></i></span>
        <div class="rg-popo-bottom">
          <div class="rg-popo hidden">
            Les tanins, c'est astringent : ça assèche les gencives.
          </div>
        </div>
      </div>
      <div class="show-tasting-group-value">
        <div class="scale-background">
          <div id="tanins-value" class="scale-value" style="width: <%= tasting.palate_tanin.to_f / 5 * 100 %>%"></div>
        </div>
      </div>
    </div>
    <div class="show-tasting-group">
      <div class="show-tasting-group-label">Alcool</div>
      <div class="show-tasting-group-value">
        <div class="scale-background">
          <div id="alcohol-value" class="scale-value" style="width: <%= ( tasting.palate_alcohol.to_f - 11 ) / 4 * 100 %>%"></div>
        </div>
      </div>
    </div>
    <div class="show-tasting-group">
      <div class="show-tasting-group-label">Puissance</div>
      <div class="show-tasting-group-value">
        <div class="scale-background">
          <div id="body-value" class="scale-value" style="width: <%= tasting.palate_body.to_f / 5 * 100 %>%"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_show_wine_details_card.html.erb
<div class="show-wine-details-card text-left">
  <div class="show-wd-group">
    <div class="show-wd-groupe-label">Cépages</div>
    <div class="show-wd-groupe-value">
      <span><%= wine.grape_variety %></span>
    </div>
  </div>
  <div class="show-wd-group">
    <div class="show-wd-groupe-label">Culture</div>
    <div class="show-wd-groupe-value">
      <span><%= wine.agricultural_mode %></span>
    </div>
  </div>
  <div class="show-wd-group">
    <div class="show-wd-groupe-label">Sulfite</div>
    <div class="show-wd-groupe-value">
      <span><%= wine.sulfites ? "oui" : "non" %></span>
    </div>
  </div>
</div>

app/views/shared/_stars.html.erb
<div class="rating" data-vote="0">

  <div class="star hidden">
    <span class="full"data-value="0"></span>
    <span class="half"data-value="0"></span>
  </div>

  <div class="star">

    <span class="full" data-value="1"></span>
    <span class="half" data-value="0.5"></span>
    <span class="selected"></span>

  </div>

  <div class="star">

    <span class="full" data-value="2"></span>
    <span class="half" data-value="1.5"></span>
    <span class="selected"></span>

  </div>

  <div class="star">

    <span class="full" data-value="3"></span>
    <span class="half" data-value="2.5"></span>
    <span class="selected"></span>

  </div>

  <div class="star">

    <span class="full" data-value="4"></span>
    <span class="half" data-value="3.5"></span>
    <span class="selected"></span>

  </div>

  <div class="star">

    <span class="full" data-value="5"></span>
    <span class="half" data-value="4.5"></span>
    <span class="selected"></span>

  </div>
</div>

app/views/shared/_tasting_fields.html.erb
<fieldset>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="long-tasting-field hidden">
    <h2>L'oeil</h2>
    <%= f.input :eye_color, label: "Couleur", collection: ["Jaune vert", "Jaune citron", "Jaune or", "Violacé", "Rubis", "Grenat"] %>
    <%= f.input :eye_intensity, label: "Intensité", collection: 1..3 %>
    <h2>Le nez</h2>
    <%= f.input :nose_condition, label: "Conditions", collection: ["Nettes", "Défaut?"] %>
    <%= f.input :nose_intensity, label: "Intensité", collection: 1..5 %>
    <%= f.input :nose_development, label: "Dévelopement", collection: ["jeune", "en cours d’évolution", "totalement évolué", "fatigué/trop vieux"] %>
  </div>
  <div class="short-tasting-field">
    <p>Notez la qualité du nez ?</p>
    <%= render 'shared/stars' %>
    <%= f.hidden_field :nose_quality, class: "hiddenRating" %>
    <%#= f.input :nose_quality, label: "Qualité du nez", collection: 0..20 %>
  </div>
  <div class="long-tasting-field hidden">
    <h2>Le palais</h2>
    <%= f.input :palate_sweetness, label: "Douceur", collection: 0..5 %>
    <%= f.input :palate_acidity, label: "Acidité", collection: 1..5%>
    <%= f.input :palate_tanin, label: "Tanins", collection: 1..5 %>
    <%= f.input :palate_alcohol, label: "Alcool", collection: 1..5 %>
    <%= f.input :palate_body, label: "Corps", collection: 1..5 %>
    <%= f.input :flavour_intensity, label: "Intensité des arômes", collection: 1..5 %>
  </div>
  <div class="short-tasting-field">
  <p>Mesurez la longueur ?</p>
    <div class="palate-finish text-center">
      <ul id="countdown">
        <li id="seconds">
          <div class="number">0</div>
          <div class="label">Seconds</div>
        </li>
      </ul>
    <%= f.hidden_field :palate_finish, class: "hiddenTime" %>
    </div>
    <%#= f.input :palate_finish, label: "Longueur en secondes", collection: 0..20 %>
    <%#= f.input :palate_quality, label: "Qualité du palais", collection: 0..20 %>
    <p>Notez la qualité du palais ?</p>
    <%= render 'shared/stars' %>
    <%= f.hidden_field :palate_quality, class: "hiddenRating" %>
    <h2>Ensemble de la dégustation</h2>
    <%= f.input :readiness, label: "Le vin, est-il prêt ?", collection: ["Trop jeune", "Peut être bu maintenant, mais potentiel de vieillissement", "A boire maintenant, ne gagnerait rien à vieillir", "Trop vieux"] %>
    <p>Notez l'équilibre du vin ?</p>
    <%= render 'shared/stars' %>
    <%= f.hidden_field :balance, class: "hiddenRating" %>
    <%#= f.input :balance, label: "Notez l'équilibre du vin ?", collection: 0..20 %>
    <%= f.input :description, label: "Description", as: :text %>
  </div>
</br>
</fieldset>

app/views/shared/_wine_and_tasting_fields.html.erb
<fieldset>
  <%= f.error_notification %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :estate_id, value: @estate %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :color, label: "Couleur", collection: ["Blanc", "Rosé", "Rouge"] %>
  <div class="long-tasting-field hidden">
  <%= f.input :alcohol, label: "Alcool" %>
  <%= f.input :agricultural_mode, label: "Méthode agricole", collection: ["Conventionnelle", "Raisonnée","HVE - Haute Valeur Environnementale", "Bio", "Biodynamique"] %>
  <%= f.input :sulfites, label: "Sulfites" %>
  <%= f.input :price_cents, label: "Prix public" %>
  <%= f.input :style, label: "Style", collection: ["Tranquille", "Effervescent", "VDN"] %>
  <%= f.input :grape_variety, label: "Cépages" %>
  <%= f.input :name, label: "Cuvée" %>
  <%= f.input :label, label: "Appellation" %>
  <%= f.input :vintage, label: "Millésime", start_year: Date.today.year - 90,
    end_year: Date.today.year, discard_day: true, discard_month: true %>
  <%= f.input :description, as: :text, label: "Description" %>
  </div>
  <h1 class="text-center">La Dégustation</h1>
  <%= f.simple_fields_for :tastings do |tasting| %>
    <%= render 'shared/tasting_fields', f: tasting %>
  <% end %>
</br>
</fieldset>

app/views/shared/_wine_fields.html.erb
<fieldset>
  <%= f.error_notification %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :estate_id, value: @estate %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :color, label: "Couleur", collection: ["Blanc", "Rosé", "Rouge"] %>
  <%= f.input :alcohol, label: "Alcool" %>
  <%= f.input :agricultural_mode, label: "Méthode agricole", collection: ["Conventionnelle", "Raisonnée","HVE - Haute Valeur Environnementale", "Bio", "Biodynamique"] %>
  <%= f.input :sulfites, label: "Sulfites" %>
  <%= f.input :price_cents, label: "Prix public" %>
  <%= f.input :style, label: "Style", collection: ["Tranquille", "Effervescent", "VDN"] %>
  <%= f.input :grape_variety, label: "Cépages" %>
  <%= f.input :name, label: "Cuvée" %>
  <%= f.input :label, label: "Appellation" %>
  <%= f.input :vintage, label: "Millésime", start_year: Date.today.year - 90,
    end_year: Date.today.year, discard_day: true, discard_month: true %>
  <%= f.input :description, as: :text, label: "Description" %>
  <%= f.input :mark, label: "Note Presse" %>
</fieldset>

app/views/shared/_wine_show.html.erb
<% @wines.each do |wine| %>
  <div class="flexgrid-item">
    <div class="sale-card card-shadow">
      <%= link_to wine_path(wine) do %>
        <div class="sale-link"></div>
      <% end %>
      <div class="sale-card-picture">
        <% if wine.photo.url != nil %>
          <%= image_tag wine.photo.url(crop: :fill) %>
          <% unless wine.tastings == [] || wine.tastings.first.general_mark.nil? %>
            <div class="general_mark"><%= wine.tastings.first.general_mark %></div>
          <% else %>
            <div class="general_mark"><%= wine.mark %></div>
          <% end %>
        <% else %>
          <%= image_tag "wine-bottle.jpeg" %>
          <% unless wine.tastings == [] || wine.tastings.first.general_mark.nil? %>
            <div class="general_mark"><%= wine.tastings.first.general_mark %></div>
          <% else %>
            <div class="general_mark"><%= wine.mark %></div>
          <% end %>
        <% end %>
      </div>
      <div class="sale-card-etiquette text-center">
        <div>
          <div class="sale-card-estate">
            <%= wine.estate.name %>
          </div>
          <div class="sale-card-cuvee">
            <%= wine.name %>
          </div>
          <div class="sale-card-vintage">
            <%= wine.vintage.year %>
          </div>
          <div class="sale-card-label">
            <%= wine.label %>
          </div>
        </div>
      </div>
    <div class="sale-card-price-cart">
      <div class="sale-card-price text-center">
        <div><%= wine.competitions.count %></div>
        <div>Compétiteurs</div>
      </div>
      <%= link_to 'Ajouter compétition', new_competition_path(wine: wine), class: "rg-btn rg-btn-success" %>
    </div>
    <div class="sale-card-price-cart">
      <div class="sale-card-price text-center">
        <div><%= wine.tastings.count %></div>
        <div>Dégustations</div>
      </div>
      <%= link_to 'Ajouter dégustation', new_wine_tasting_path(wine_id: wine.id), class: "rg-btn rg-btn-success" %>
    </div>
  </div>
    </div>
<% end %>