config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :competitions, only: [:new, :create]
  resources :estates
  resources :wines do
    resources :tastings do
      resources :tasting_aromas
    end
  end
  get "wine_to_taste" => "wines#wine_to_taste"
  get "wine_tasted" => "wines#wine_tasted"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="wrapper wrapper-lightyellow" id="home-acs-section">
  <div class="flexgrid-container text-center">
    <div class="home-card">
      <div class="flexgrid-flexbox">
        <div class="flexgrid-item">
          <div class="sale-card card-shadow">
            <%= link_to estates_path do %>
              <div class="sale-link"></div>
            <% end %>
            <div class="sale-card-etiquette text-center">
              <div>
                <div class="sale-card-estate">
                  Liste de mes domaines
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="flexgrid-flexbox">
        <div class="flexgrid-item">
          <div class="sale-card card-shadow">
            <%= link_to wines_path do %>
              <div class="sale-link"></div>
            <% end %>
            <div class="sale-card-etiquette text-center">
              <div>
                <div class="sale-card-estate">
                  Liste des vins
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="flexgrid-item">
          <div class="sale-card card-shadow">
            <%= link_to wine_tasted_path do %>
              <div class="sale-link"></div>
            <% end %>
            <div class="sale-card-etiquette text-center">
              <div>
                <div class="sale-card-estate">
                  Classement des vins dégustés
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="flexgrid-item">
          <div class="sale-card card-shadow">
            <%= link_to wine_to_taste_path do %>
              <div class="sale-link"></div>
            <% end %>
            <div class="sale-card-etiquette text-center">
              <div>
                <div class="sale-card-estate">
                  Vins à déguster
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>