config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :competitions, only: [:new, :create]
  resources :estates
  resources :wines do
    resources :tastings do
      resources :tasting_aromas
    end
  end
  get "wine_to_taste" => "wines#wine_to_taste"
  get "wine_tasted" => "wines#wine_tasted"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estate.rb
class Estate < ApplicationRecord
  belongs_to :user
  has_many :wines, dependent: :destroy
  accepts_nested_attributes_for :wines, allow_destroy: true

  validates :name, presence: true
end

app/controllers/estates_controller.rb
class EstatesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index]

  def index
    @estates = policy_scope(Estate).order(created_at: :desc)
  end

  def show
    @estate = Estate.find(params[:id])
    @wines = @estate.wines
    authorize @estate
  end

  def new
    @estate = Estate.new
    @estate.user = current_user
    @wine = @estate.wines.build
    @tasting = @wine.tastings.build
    @submit_label = "Ajouter le domaine"
    authorize @estate
  end

  def create
    @estate = Estate.new(estate_params)
    @estate.user = current_user
    @submit_label = "Ajouter le domaine"
    @estate.save
    authorize @estate
    if @estate.save
      flash[:notice] = "Domaine créée"
      redirect_to estate_path(@estate)
    else
      flash[:alert] = "Ça a planté, mec!"
      render :new
    end
  end

  def edit
    @estate = Estate.find(params[:id])
    @submit_label = "Modifier le domaine"
    authorize @estate
  end

  def update
    @estate = Estate.find(params[:id])
    @submit_label = "Modifier le domaine"
    @estate.update(estate_params)
    authorize @estate
    if @estate.save
      flash[:notice] = "Update ok!!"
      redirect_to estates_path
    else
      flash[:alert] = "Mais c'est pas bien rempli, tout ça!!"
      render :edit
    end
  end

  def destroy
    @estate = Estate.find(params[:id])
    @estate.delete
    authorize @estate
    redirect_to estates_path
  end

  private
  def estate_params
    params.require(:estate).permit(
        :id,
        :name,
        :description,
        :mark,
        :user_id,
        wines_attributes: [:id, :photo, :photo_cache, :color, :alcohol, :agricultural_mode,
          :sulfites, :price_cents, :style, :grape_variety, :name, :label, :vintage,
          :description, :mark, :estate_id, :user_id, :_destroy,
          tastings_attributes: [
            :nose_quality, :palate_finish, :palate_quality, :readiness, :balance,
            :description, :eye_color, :eye_intensity, :nose_condition, :nose_intensity,
            :nose_development, :palate_sweetness, :palate_acidity, :palate_tanin,
            :palate_alcohol, :palate_body, :flavour_intensity, :wine_id, :user_id,
            :_destroy
          ]])
  end
end

app/helpers/estates_helper.rb
module EstatesHelper
end

app/views/estates/_wine_fields.html.erb
<fieldset>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.input :name, label: "Nom du vin" %>
  <%= f.input :label, label: "Appellation" %>
  <%= f.input :vintage, label: "Millésime", start_year: Date.today.year - 90,
    end_year: Date.today.year, discard_day: true, discard_month: true %>
  <%= f.input :grape_variety, label: "Cépages" %>
  <%= f.input :color, label: "Couleur", collection: ["Blanc", "Rosé", "Rouge"] %>
  <%= f.input :style, label: "Style", collection: ["Tranquille", "Effervescent", "VDN"] %>
  <%= f.input :mark, label: "Note", colletion: 0..20 %>
  <%= f.input :description, as: :text, label: "Description" %>
  <%= f.input :agricultural_mode, label: "Méthode agricole", collection: ["Conventionnelle", "Raisonnée","HVE - Haute Valeur Environnementale", "Bio", "Biodynamique"] %>
  <%= f.input :sulfites, label: "Sulfites" %>
  <%= f.input :price_cents, label: "Prix public" %>
  <h2>La Dégustation</h2>
  <%= f.simple_fields_for :tastings do |tasting| %>
    <%= render 'tasting_fields', f: tasting %>
  <% end %>
</br>
</fieldset>

app/views/estates/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <%= simple_form_for(@estate) do |f| %>
        <%= f.input :name, label: "Nom du domaine" %>
        <%= f.input :description, label: "Description", as: :text %>
        <div class="text-center"><span class="flex padded-top padded-bot"><%= f.button :submit, "#{@submit_label}", class: "btn btn-primary" %></span></div>
      <% end %>
    </div>
  </div>
</div>

app/views/estates/index.html.erb
<div class="wrapper wrapper-lightyellow" id="home-acs-section">
  <div class="flexgrid-container text-center">
    <div class="home-card">
      <h2 class="text-center">Liste de mes domaines</h2>
      <div class="flexgrid-flexbox">
        <div class="flexgrid-item">
          <div class="sale-card card-shadow">
            <%= link_to new_estate_path do %>
              <div class="sale-link"></div>
            <% end %>
            <div class="sale-card-etiquette text-center">
              <div>
                <div class="sale-card-estate">
                  <%= image_tag "plus_icon.png" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% @estates.each do |estate| %>
          <div class="flexgrid-item">
            <div class="sale-card card-shadow">
              <%= link_to estate_path(estate) do %>
                <div class="sale-link"></div>
              <% end %>
              <div class="sale-card-etiquette text-center">
                <div>
                  <div class="sale-card-estate">
                    <%= estate.name %>
                  </div>
                  <div class="sale-card-cuvee">
                    <%= estate.description %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/estates/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Le domaine</h1>
      <%= simple_form_for(@estate) do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, label: "Nom du domaine" %>
        <%= f.input :description, label: "Description", as: :text %>
        <h1 class="text-center">Le vin</h1>
        <%= f.simple_fields_for :wines do |wine| %>
          <%= render 'shared/wine_fields', f: wine %>
        <% end %>
        <div class="text-center"><span class="flex padded-top padded-bot"><%= f.button :submit, "#{@submit_label}", class: "btn btn-primary" %></span></div>
      <% end %>
    </div>
  </div>
</div>

app/views/estates/show.html.erb
<div class="wrapper">
  <div class="flexgrid-container text-center">
    <h2 class="text-center"><%= @estate.name %></h2>
    <div class="flexgrid-flexbox">
      <div class="wrapper wrapper-lightyellow" id="home-acs-section">
        <div class="flexgrid-container text-center">
          <!-- <div class="home-card"> -->
          <h2 class="text-center">Liste des Vins</h2>
          <div class="flexgrid-flexbox">
            <div class="flexgrid-item">
              <div class="sale-card card-shadow">
                <!-- change method to be able to add domain or select when creating a wine-->
                <%= link_to new_wine_path(estate: @estate) do %>
                  <div class="sale-link"></div>
                <% end %>
                <div class="sale-card-etiquette text-center">
                  <div>
                    <div class="sale-card-estate">
                      <%= image_tag "plus_icon.png" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <% @wines.each do |wine| %>
              <div class="flexgrid-item">
                <div class="sale-card card-shadow">
                  <%= link_to wine_path(wine) do %>
                    <div class="sale-link"></div>
                  <% end %>
                  <div class="sale-card-picture">
                    <% if wine.photo.url != nil %>
                      <%= image_tag wine.photo.url(crop: :fill) %>
                      <% unless wine.tastings == [] || wine.tastings.last.general_mark.nil? %>
                        <div class="general_mark"><%= wine.tastings.last.general_mark %></div>
                      <% end %>
                    <% else %>
                      <%= image_tag "wine-bottle.jpeg" %>
                    <% end %>
                    </div>
                    <div class="sale-card-etiquette text-center">
                      <div>
                        <div class="sale-card-estate">
                          <%= wine.estate.name %>
                        </div>
                        <div class="sale-card-cuvee">
                          <%= wine.name %>
                        </div>
                        <div class="sale-card-vintage">
                          <%= wine.vintage.year %>
                        </div>
                        <div class="sale-card-label">
                          <%= wine.label %>
                        </div>
                      </div>
                    </div>
                  <div class="sale-card-price-cart">
                    <div class="sale-card-price text-center">
                      <div><%= wine.competitions.count %></div>
                      <div>Compétiteurs</div>
                    </div>
                    <%= link_to 'Ajouter compétition', new_competition_path(wine: wine), class: "rg-btn rg-btn-success" %>
                  </div>
                  <div class="sale-card-price-cart">
                    <div class="sale-card-price text-center">
                      <div><%= wine.tastings.count %></div>
                      <div>Dégustations</div>
                    </div>
                    <%= link_to 'Ajouter dégustation', new_wine_tasting_path(wine_id: wine.id), class: "rg-btn rg-btn-success" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>