config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :competitions, only: [:new, :create]
  resources :estates
  resources :wines do
    resources :tastings do
      resources :tasting_aromas
    end
  end
  get "wine_to_taste" => "wines#wine_to_taste"
  get "wine_tasted" => "wines#wine_tasted"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tasting.rb
class Tasting < ApplicationRecord
  belongs_to :user
  belongs_to :wine, optional: true

  mount_uploader :photo, PhotoUploader

  def palate_finish_desc
    if palate_finish <= 3
      return "courte"
    elsif palate_finish <= 5
      return "moyenne (-)"
    elsif palate_finish <= 7
      return "moyenne"
    elsif palate_finish <= 9
      return "moyenne (+)"
    else
      return "longue"
    end
  end

  def stars_rating(mark)
    if mark.nil?
      return nil
    else
      rating = mark
      full_stars = rating.to_i
      if rating - rating.to_i > 0.74
        full_stars += 1
        half_star = 0
      elsif rating - rating.to_i > 0.24
        half_star = 1
      else
        half_star = 0
      end
      empty_stars = 5 - full_stars - half_star
    end
    return [full_stars, half_star, empty_stars]
  end

  def body
    if self.palate_body.nil?
      return nil
    else
      body = self.palate_body
      case body
        when 1 then "Léger"
        when 2 then "Moyen (-)"
        when 3 then "Moyen"
        when 4 then "Moyen (+)"
        when 5 then "Puissant"
        else "Mauvaise réponse"
      end
    end
  end

  def general_mark
    ponderation = 0
    general_mark = 0
    complement = ""
    case readiness
      when "Trop jeune" then complement = "+"
      when "Peut être bu maintenant, mais potentiel de vieillissement" then complement = "+"
      when "Trop vieux" then complement = "-"
      else complement = ""
    end
    unless nose_quality.nil?
      ponderation += 15
      general_mark += nose_quality*3
    end
    unless palate_quality.nil?
      ponderation += 40
      general_mark += palate_quality*8
    end
    unless palate_finish.nil?
      ponderation += 20
      if palate_finish <=10
        general_mark += palate_finish*2
      else
        general_mark += 20
      end
    end
    unless balance.nil?
      ponderation += 25
      general_mark += balance*5
    end
    if general_mark == 0
      complement = " note"
    else
      general_mark = 100*general_mark/ponderation
    end
    return general_mark.to_i.to_s + complement
  end
end

app/controllers/tastings_controller.rb
class TastingsController < ApplicationController
  def index
    @tastings = policy_scope(Tasting).order(created_at: :desc)
  end

  def new
    @wine = Wine.find(params[:wine_id])
    @tasting = @wine.tastings.new
    @tasting.user = current_user
    @submit_label = "Ajouter une dégustation"
    authorize @tasting
  end

  def create
    @wine = Wine.find(params[:wine_id])
    @tasting = @wine.tastings.new(tasting_params)
    # @tasting.nose_quality = params[:wine][:tastings_attributes]["0"]["nose_quality"].to_f
    # @tasting.palate_quality = params[:wine][:tastings_attributes]["0"]["palate_quality"].to_f
    # @tasting.balance = params[:wine][:tastings_attributes]["0"]["balance"].to_f
    @tasting.user = current_user
    @submit_label = "Ajouter une dégustation"
    authorize @tasting
    if @tasting.save
      flash[:notice] = "Dégustation créée"
      redirect_to wine_path(@wine)
    else
      flash[:alert] = "Ça a planté, mec!"
      render :new
    end
  end

  def edit
    @tasting = Tasting.find(params[:id])
    @submit_label = "Modifier la dégustation"
    authorize @tasting
  end

  def update
    @tasting = Tasting.find(params[:id])
    @submit_label = "Modifier la dégustation"
    @tasting.update(tasting_params)
    authorize @tasting
    if @tasting.save
      flash[:notice] = "Update ok!!"
      redirect_to tastings_path
    else
      flash[:alert] = "Mais c'est pas bien rempli, tout ça!!"
      render :edit
    end
  end

  def destroy
    @tasting = Tasting.find(params[:id])
    @tasting.delete
    authorize @tasting
    redirect_to tastings_path
  end

  private
  def tasting_params
    params.require(:tasting).permit(:eye_color, :nose_condition, :nose_intensity,
      :nose_development, :nose_quality, :palate_sweetness, :palate_acidity,
      :palate_tanin, :palate_alcohol, :palate_body, :flavour_intensity,
      :palate_finish, :palate_quality, :readiness, :balance, :description, :wine_id)
  end
end

app/helpers/tastings_helper.rb
module TastingsHelper
end

app/views/tastings/create.html.erb
<h1>Tastings#create</h1>
<p>Find me in app/views/tastings/create.html.erb</p>

app/views/tastings/destroy.html.erb
<h1>Tastings#destroy</h1>
<p>Find me in app/views/tastings/destroy.html.erb</p>

app/views/tastings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <%= simple_form_for(@tasting) do |f| %>
        <h2>Sélectionner un vin</h2>
          <%= f.association :wine, label: "Vin"%>
        <h2>L'oeil</h2>
        <%= f.input :eye_color, label: "Couleur", collection: ["Jaune vert", "Jaune citron", "Jaune or", "Violacé", "Rubis", "Grenat"] %>
        <%= f.input :eye_intensity, label: "Intensité", collection: 1..3 %>
        <h2>Le nez</h2>
        <%= f.input :nose_condition, label: "Conditions", collection: ["Nettes", "Défaut?"] %>
        <%= f.input :nose_intensity, label: "Intensité", collection: 1..5 %>
        <%= f.input :nose_development, label: "Dévelopement", collection: ["jeune", "en cours d’évolution", "totalement évolué", "fatigué/trop vieux"] %>
        <%= f.input :nose_quality, label: "Qualité du nez", collection: 0..20 %>
        <h2>Le palais</h2>
        <%= f.input :palate_sweetness, label: "Douceur", collection: 0..5 %>
        <%= f.input :palate_acidity, label: "Acidité", collection: 1..5%>
        <%= f.input :palate_tanin, label: "Tanins", collection: 1..5 %>
        <%= f.input :palate_alcohol, label: "Alcool", collection: 1..5 %>
        <%= f.input :palate_body, label: "Corps", collection: 1..5 %>
        <%= f.input :flavour_intensity, label: "Intensité des arômes", collection: 1..5 %>
        <%= f.input :palate_finish, label: "Longueur en secondes", collection: 0..20 %>
        <%= f.input :palate_quality, label: "Qualité du palais", collection: 0..20 %>
        <h2>Ensemble de la dégustation</h2>
        <%= f.input :readiness, label: "Le vin, est-il prêt ?", collection: ["Trop jeune", "Peut être bu maintenant, mais potentiel de vieillissement", "A boire maintenant, ne gagnerait rien à vieillir", "Trop vieux"] %>
        <%= f.input :readiness, label: "Notez l'équilibre du vin ?", collection: 0..20 %>
        <%= f.input :description, label: "Description", as: :text %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="text-center"><span class="flex padded-top padded-bot"><%= f.button :submit, "#{@submit_label}", class: "btn btn-primary" %></span></div>
      <% end %>
    </div>
  </div>
</div>

app/views/tastings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <table>
        <thead>
          <tr>
            <th>Index</th>
            <th>Photo</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @tastings.each do |tasting| %>
            <tr>
              <td><%= tasting.id %></td>
              <!-- <td><%= tasting.description %></td> -->
              <td><%= tasting.wine.name %></td>
              <td>
                <% if tasting.photo.url != nil %>
                  <%= image_tag tasting.photo.url(:small) %></td>
                <% end %>
              <td>
                <% if policy(tasting).edit? %>
                  <%= link_to 'éditer', edit_tasting_path(tasting) %>
                <% end %>
              </td>
              <td>
                <% if policy(tasting).destroy? %>
                  <%= link_to 'supprimer', tasting, method: :delete, data: { confirm: "Etes-vous sûr ?" } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <p><%= link_to 'Ajouter une dégustation', new_tasting_path %></p>
    </div>
  </div>
</div>

app/views/tastings/new.html.erb
<div class="container">
  <%= render 'shared/radio_button_choice' %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
      <%= simple_form_for [@wine, @tasting] do |f| %>
        <%= render 'shared/tasting_fields', f: f %>
        <div class="text-center"><span class="flex padded-top padded-bot"><%= f.button :submit, "#{@submit_label}", class: "btn btn-primary" %></span></div>
      <% end %>
    </div>
  </div>
</div>

app/views/tastings/update.html.erb
<h1>Tastings#update</h1>
<p>Find me in app/views/tastings/update.html.erb</p>